# Generated by Django 5.2.8 on 2026-01-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='products/default.png', null=True, upload_to='products/'),
        ),
    ]
